### ISSUE TITLE
Support streaming requests/responses

### ISSUE THREAD

**Issue by scothis** [cujojs/rest#101]
Using the WHATWG Streams spec as a base https://streams.spec.whatwg.org/

We'll have to use the reference implementation until it's implemented by vendors. The Node Steams API is also a possibility, but I'd rather use an API that has a chance of native platform support. In either case, it should be possible to convert between the two APIs.

**Comment by davidchase** [comment]
:+1: for this

**Comment by stayfool** [comment]
Is this problem solved?

**Comment by DailunCheng** [comment]
Also want to know if streaming is supported or not. If not, is there any notable alternative? @scothis

**Comment by scothis** [comment]
rest.js is no longer maintained
