### ISSUE TITLE
Support binary entities

### ISSUE THREAD

**Issue by scothis** [cujojs/rest#103]
rest.js currently doesn't not handle binary entities very well. Binary data should have first class support equal to text bases entities. Supporting binary entities will be easier with #101, although it doesn't block support either.

The xhr client in particular will be curious to support as it XHR API seems to prefer foreknowledge of the response type. See #78 for inspiration.

**Comment by bldrvnlw** [comment]
I was trying to handle a binary response with cujojs/rest 2.0.0 but couldn't get it working and then found this open issue. Should I just go back to a raw XMLHttpRequest for this or is there another solution?

**Comment by scothis** [comment]
rest.js is no longer maintained
