### ISSUE TITLE
Different access to headers between Node and Browser

### ISSUE THREAD

**Issue by asimpson** [cujojs/rest#107]
I'm doing a default request and in Node I'm seeing the `Link` Header that I want to parse, but I'm not seeing the `Link` Header at all in the browser using browserify.

What am I missing?

**Comment by scothis** [comment]
@asimpson I'm not sure why the Link header would not be available in the browser. XMLHttpRequest does filter out some headers, however, Link is not one of them.

Do you have a public endpoint I could hit to test a few things? Additionally, double check with the network inspector in the browser to double check the Link header is actually being sent by the server.

**Comment by asimpson** [comment]
Turns out I wasn't properly using `Access-Control-Expose-Headers` in my server app to explicitly expose the `Link` header for any request. Thanks for the response!

**Comment by scothis** [comment]
That would do it.

Thanks for posting this issue, hopefully other people will find it in the future when they hit the same hurdle.
