### ISSUE TITLE
rest/util/uriTemplate silently fails to expand variable if provided value is a number

### ISSUE THREAD

**Issue by itkach** [cujojs/rest#108]
Consider these [mocha](http://mochajs.org/) tests:
```javascript
var assert = require("assert"),
    uriTemplate = require('rest/util/uriTemplate'),
    UrlBuilder = require('rest/UrlBuilder');

var expected = 'http://example.com/123',
    path = 'http://example.com/{a}',
    params = {a: 123};

it('builds url with UrlBuilder', function() {
  var url = new UrlBuilder(path, params).build();
  assert.equal(expected, url);
});

it('builds url with uriTemplate', function() {
  var url = uriTemplate.expand(path, params);
  assert.equal(expected, url);
});

```

With rest.js 1.3.0 the output is

```
  ✓ builds url with UrlBuilder 
  1) builds url with uriTemplate

  1 passing (12ms)
  1 failing

  1)  builds url with uriTemplate:
     AssertionError: 'http://example.com/123' == 'http://example.com/'
```
uriTemplate silently interpreted integer value 123 as an empty string. This is surprising behavior. Number should be converted to string and that string value should be used for variable expansion (isn't that what happens with simple variable expansion for arrays?), or at least warning should be logged or error raised.

**Comment by scothis** [comment]
@itkach I agree that should work. The RFC only deals with strings, dictionaries and lists, which is why I didn't find this issue. It should be a fairly easy fix though, I'll get something up this weekend.

**Comment by scothis** [comment]
@itkach this is fixed on the dev branch, please take it for a spin and reopen this issue if you encounter any problems.

**Comment by itkach** [comment]
> please take it for a spin

looks good so far
