### ISSUE TITLE
Error when attempting to replay a request

### ISSUE THREAD

**Issue by pvormittag** [cujojs/rest#114]
I have a custom OAuth 2.0 interceptor, which is based off https://github.com/cujojs/rest/blob/master/interceptor/oAuth.js

If the client sends an invalid or expired token on the request, the server appropriately returns a 401. However if I try to replay the request just as the original OAuth interceptor does (https://github.com/cujojs/rest/blob/master/interceptor/oAuth.js#L130), An "undefined is not a function" Error is thrown. Any thoughts to why this happens? I've posted the code for my custom OAuth interceptor below and I am running in a browser environment (Chrome 41).

It may be helpful to know the authentication flow is not 3-legged or using the `implicit` grant, but a custom grant which allows insecure JavaScript to communicate directly with the API.

```js
'use strict';

var interceptor = require('rest/interceptor');
var when = require('when');
var rest = require('rest');
var OAuthError = require('../Errors/OAuthError');

function authorization (token) {
  return token.token_type + ' ' + token.access_token;
}

module.exports = interceptor({
  request: function (request, config) {
    var tokenStore = config.harvest.accessTokenStore;
    request.headers = request.headers || {};

    if (!tokenStore.hasToken()) {
      // No token found, request an access token.
      
      return config.harvest.requestAccessToken().then(function (token) {
        tokenStore.putToken(token);
        request.headers.Authorization = authorization(token);
        return request;
      }).catch(function (response) {
        return when.reject(response);
      });
    } else if (tokenStore.hasExpiredToken() && tokenStore.refreshToken()) {
      // The token has expired and a refresh token is available, attempt
      // to refresh the token.
      
      var token = tokenStore.token();
      var params = { refresh_token: token.refresh_token };
      return config.harvest.requestAccessToken(params).then(function (token) {
        tokenStore.putToken(token);
        request.headers.Authorization = authorization(token);
        return request;
      }).catch(function (response) {
        return when.reject(response);
      });
    } else {
       // The token is valid, so use it.
        
      request.headers.Authorization = authorization(tokenStore.token());
      return request;
    }
  },

  response: function (response, config, client) {
    var tokenStore = config.harvest.accessTokenStore;

    if (response.status.code === 401) {

      // Token likely expired, attempt to reauthorize.

      tokenStore.forgetToken();

      return config.harvest.requestAccessToken().then(function (token) {
        tokenStore.putToken(token);
        return client(response.request);
      });
    } else if (response.status.code === 403) {
      return when.reject(response);
    }

    return response;
  }
});
```

**Comment by scothis** [comment]
@pvormittag nothing immediately jumps out. Can you attach the stack trace? I assume the method names on harvest and tokenStore are correct.

**Comment by pvormittag** [comment]
@scothis reviewing the `stack` variable on the error object, I get more detail on the error. The error message is `client is not a function`. It appears the `client` argument passed to the `response` method on the interceptor is not a client object itself, rather a payload object or another object I'm unaware of, which contains a `client` variable. To illustrate:

```js
// response method within a contrived interceptor module

response: function (response, config, client) {
  // This throws an error as `client` is not a client object, rather
  // an object which holds a reference to the intercepted client.
  client(response.request).

  // This works.
  client.client(response.request);
}
```

Is this expected functionality? If so, the provided `oAuth.js` interceptor may also throw an error due to this discrepancy.

**Comment by scothis** [comment]
Yea, the third argument should be 'meta' instead of 'client', this was a change made just before 1.0, which means you found an old bug in the oAuth interceptor.  I assume after the change, your interceptor is working.

**Comment by pvormittag** [comment]
Yes the interceptor works after changing `client(response.request)` to `meta.client(response.request)`.
