### ISSUE TITLE
GET request with array params

### ISSUE THREAD

**Issue by rschellhorn** [cujojs/rest#124]
Given:

```
var params = {
  arg1: ['foo', 'bar']
};

rest(path: '/foo', params: params)
```

Will call an url: `/foo?arg1=%5Bfoo%2Cbar%5D`

It should create an url: `/foo?arg1=foo&arg1=bar`

The UrlBuilder (https://github.com/cujojs/rest/blob/master/UrlBuilder.js#L51) should take arrays into account like e.g. https://github.com/Gozala/querystring/blob/master/encode.js#L50

**Comment by scothis** [comment]
rest.js is no longer maintained
