### ISSUE TITLE
throws strings rather than Error objects

### ISSUE THREAD

**Issue by tmcw** [cujojs/rest#127]
https://github.com/cujojs/rest/blob/master/interceptor/mime.js#L67

As [eslint hath spoken](http://eslint.org/docs/rules/no-throw-literal.html), Error objects give tracebacks and strings don't.

**Comment by scothis** [comment]
Fully agree, Will address in 2.0

**Comment by tmcw** [comment]
2.0.0 is out, looks like [strings are still being thrown](https://github.com/cujojs/rest/blob/4bd359df2df845eda628d2256fd06bc4a1f5009c/interceptor/mime.js#L23).

**Comment by scothis** [comment]
Correct. Similar to #146 where rejected promises also do not contain Errors, but response objects. Rethinking error handling is something that should be done, but is a major breaking change. I'm not convinced the pain of making this change is worth the benefit.

If I were writing rest.js today, I wouldn't have done it this way, but it's also not horrible.

**Comment by cjthompson** [comment]
Since these are being thrown within interceptors, wouldn't it be possible to just have a separate interceptor that throws `Error`s instead, or add a config parameter like `.wrap(mime, { throwErrors: true })`?
