### ISSUE TITLE
Testing with mocha in node env

### ISSUE THREAD

**Issue by datpham23** [cujojs/rest#135]
Hi i'm currently trying to test some utilities that has rest.js as a dependency. I'm mocking out the document/window w/ jsdom however i'm still getting this error message : 

```
TypeError: Cannot read property 'origin' of undefined
      at Object.UrlBuilder.fullyQualify (node_modules/rest/UrlBuilder.js:128:23)
      at Object.UrlBuilder.parts (node_modules/rest/UrlBuilder.js:185:16)
      at node_modules/rest/UrlBuilder.js:220:53

```

Is there anything else i need to manually mock?
Thanks,
Dat

**Comment by scothis** [comment]
`fullyQualify` is only supported in browsers, as in Node there isn't a base url to be relative to. My guess is that you have a partially polyfilled `window.location` object. If the location object is completely missing the method will shortcut itself.

**Comment by datpham23** [comment]
After some digging into the UrlBuilder code. I realized the origin is just using the window.location object.
If you mock it to something like this it should. Thanks for the help!

```
window.location = {
  hash: "",
  host: "localhost:8080",
  hostname: "localhost",
  href: "http://localhost:8080/",
  origin: "http://localhost:8080",
  pathname: "/",
  port: "8080",
  protocol: "http:",
  search: ''
};

```

**Comment by kevinzwhuang** [comment]
If you are reading this and finding yourself with this exact same error using https://github.com/facebook/jest, try setting the `testURL` option in your package.json config for jest to something like `http://localhost:8000`, and it should fix the problem.

 - Read more here https://facebook.github.io/jest/docs/configuration.html#testurl-string
