### ISSUE TITLE
Interceptor for limiting number of parallel requests

### ISSUE THREAD

**Issue by buildjosh** [cujojs/rest#136]
Any ideas on how to ago about this?

I have an api client that needs to stay under 50 requests/second. I imagine I would need access to the httpAgent that is being used as I don't want to apply it to the global agent.

**Comment by buildjosh** [comment]
Actually I think I figured it out using defaultRequest.

`
var agent = new http.Agent({
    maxSockets: (process.env.MAX_API_SOCKETS || 25 / process.env.WEB_CONCURRENCY || 1)
});

.wrap(defaultRequest, { mixin: { agent: agent } })
`

**Comment by scothis** [comment]
Im not very familiar with agents, but the looks like it would work.

Another way is to create a custom interceptor that hooks into the request phase and uses [`when/guard`](https://github.com/cujojs/when/blob/master/docs/api.md#limiting-concurrency) to limit the concurrency.

Both of these options will limit the number of concurrent requests but not restrict to an actual throughput rate. Doing that is possible based on the same principals, but would require a custom strategy to release the request.

**Comment by scothis** [comment]
rest.js is no longer maintained
