### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tmcw** [cujojs/rest#137]
![2016-03-21 at 12 14 pm](https://cloud.githubusercontent.com/assets/32314/13925419/9bc533c2-ef5e-11e5-827a-2c3b53c2f707.png)

Currently it seems that `rest`'s dependency on [when](https://github.com/cujojs/when) breaks [React Native](https://facebook.github.io/react-native/)'s haste packager. I'm not sure exactly which pattern breaks Native.

**Comment by scothis** [comment]
The path to `./dist/browser/when.js` is defined in [when's package.json](https://github.com/cujojs/when/blob/ade63932fd32eb628fea80222af3004fe42a8c60/package.json#L76). Is there a reason why React Native is trying to use the browser configuration?

cc @briancavalier

**Comment by scothis** [comment]
rest.js 2.0 will not depend on when.js, so this should no longer be an issue.

**Comment by nitaliano** [comment]
@scothis I'm still having problems with React Native since it is fetch based. Would you be able to a PR to adds support for RN?
