### ISSUE TITLE
URL Encoding works incorrectly 

### ISSUE THREAD

**Issue by tmcw** [cujojs/rest#138]
https://github.com/cujojs/rest/blob/master/util/uriEncoder.js#L54-L56

```
> '\n'.charCodeAt(0).toString(16).toUpperCase()
'A'
> encodeURIComponent('\n')
'%0A'
```

This code does not properly 0-pad characters that turn into single-char hex strings.

Upstream of https://github.com/mapbox/mapbox-sdk-js/issues/59

**Comment by scothis** [comment]
Fixed in v1.3.2
