### ISSUE TITLE
rest params don't work

### ISSUE THREAD

**Issue by Fornori** [cujojs/rest#145]
Hello. I have the code like this:
`rest({
            method: 'GET',
            path: 'http://localhost:7777/api/users',
            params: {
                size: "2"
            }
        });`

As result I expect some think like this: http://localhost:7777/api/users?size=2 but i get. with out any params. So params only work with post|put|delete?

**Comment by rashtao** [comment]
I think you need this: [template interceptor](https://github.com/cujojs/rest/blob/4bd359df2df845eda628d2256fd06bc4a1f5009c/docs/interceptors.md#module-rest/interceptor/template)

[here](https://github.com/cujojs/rest/blob/4bd359df2df845eda628d2256fd06bc4a1f5009c/test/interceptor/template-test.js) some examples

**Comment by scothis** [comment]
One of the major changes in rest.js 2.0 is that request params are no longer automatically applied to the path. The same behavior is available in the `rest/interceptor/params` interceptor.

**Comment by scothis** [comment]
rest.js is no longer maintained
