### ISSUE TITLE
promise was rejected with a non-error

### ISSUE THREAD

**Issue by rashtao** [cujojs/rest#146]
Using [Error Code Interceptor](https://github.com/cujojs/rest/blob/master/docs/interceptors.md#error-code-interceptor) in `node v6.2.2` generates these warning logs:

``` sh
(node:3220) Warning: a promise was rejected with a non-error: [object Object]
```

The promise is rejected with an `Object` and this prevents an accurate use of [filtered catch](http://bluebirdjs.com/docs/api/catch.html#filtered-catch).

It would be nice to have typed errors and promises rejected e.g. with `HttpRestError`, so allowing the following:

``` js
client = rest.wrap(errorCode);
client({})
    .then((v) => applicationLogicMethod(v)) // application logic that throws MyError
    .catch(MyError, (e) => handleMyError(e))
    .catch(HttpRestError, (e) => handleHttpRestError(e));
```

**Comment by scothis** [comment]
The Promises/A+ and ES6 specs do not mandate, or even suggest, that the rejection reason be an Error instance. It is a best practice pushed by parts of the community. Likewise, filtered catch is not part of the spec.

I agree that it is a good practice to only reject with Errors, the practice of using a rejected promise as a signal for application level errors predates this practice.  Migrating to use Errors would be a major API change, and I'm not convinced right now that the cost is worth the benefit. I'm open to being persuaded though.

**Comment by scothis** [comment]
rest.js is no longer maintained
