### ISSUE TITLE
Does this library work with `await`?

### ISSUE THREAD

**Issue by RichardJECooke** [cujojs/rest#148]
Can I just call `const result = await rp(options)` or do I have to call `rp(options).then(...)` to actually trigger the request to start?

Some libraries, like superagent, won't work without the latter syntax.

It would be wonderful if you added this info to your home page readme.

**Comment by scothis** [comment]
There are a couple corners of rest.ja that wait for a subscriber to the promise before starting the work, mostly when dealing with relationships in hypermedia resources, like HAL.  Otherwise it should just work.  Let me know if you see something odd.

**Comment by scothis** [comment]
rest.js is no longer maintained
