### ISSUE TITLE
use and configure timeout

### ISSUE THREAD

**Issue by awb99** [cujojs/rest#150]
Can someone tell me how I can use the timeout, and how to configure it.
A short example would be GREAT!

Thanks!

**Comment by mihaicostin** [comment]
it should be something like this, if I'm not mistaking:
```
const rest = require('rest');
const timeout = require('rest/interceptor/timeout');

let restClient = rest.wrap(timeout, {timeout: 1000}); //timeout of 1 sec
```

**Comment by scothis** [comment]
rest.js is no longer maintained
