### ISSUE TITLE
jquery.rest.js: create method Uncaught Error

### ISSUE THREAD

**Issue by ropean** [cujojs/rest#151]
`
var apiClient = new $.RestClient('/api/');

apiClient.add("GapDetail")

apiClient.GapDetail.add("test")

var item = { value : 3},
                rows = [{"GapNumber":1,"GapUnit":"DAY","uid":0,"boundindex":0,"uniqueid":"2817-28-31-24-273121","visibleindex":0,"GapKey":3},{"GapNumber":2,"GapUnit":"DAY","uid":1,"boundindex":1,"uniqueid":"2018-24-26-27-222024","visibleindex":1,"GapKey":3}];

apiClient.GapDetail.test.create({ Key: item.value, GapDetails: rows }).done(function (data, textStatus, xhrObject) {
                alert('I have data: ' + data);
            });

`

when execute the js, occured error:

jquery.rest.js:7 Uncaught Error: ERROR: jquery.rest: Invalid number of ID arguments, required 1 or 2, provided 0

please fix the bug, thanks!

**Comment by scothis** [comment]
Are you looking for https://github.com/jpillora/jquery.rest?
