### ISSUE TITLE
npm installation error for rest

### ISSUE THREAD

**Issue by kaushikkingman** [cujojs/rest#152]
Hi,
I am working behind a corporate firewall. While installing node_modules, my most of the modules get fetched easily [with proxy settings in .npmrc file], but dependency for this rest cannot be fetched from cujojs.

I have attached a screenshot of the same.

Kaushik
![npm log](https://cloud.githubusercontent.com/assets/22612473/19068465/611d9d40-8a40-11e6-900d-6db1bd99f919.JPG)

**Comment by scothis** [comment]
Some of the development dependencies are pulled directly from github because they are not published to npm.  You should only need these if you developing on rest.js and need to run the test suite.

**Comment by scothis** [comment]
rest.js is no longer maintained
