### ISSUE TITLE
Improve timeout Error

### ISSUE THREAD

**Issue by briancavalier** [cujojs/rest#154]
Hey @scothis, are you open to a PR that switches this [error timeout string value](https://github.com/cujojs/rest/blob/master/interceptor/timeout.js#L41) to an Error, or perhaps a custom TimeoutError?

I know you've mentioned revamping error handling on a larger scale in #127 and #146, so this would be a shorter term change until then.

In production code, we're finding that it'd be helpful to have a bit more information at the point of timeout, in order to be able to log and debug more effectively.  As a simple example, we like to be able to log the timeout milliseconds along with the failure without having to thread it through the interceptor chain ourselves (maybe there is already a way to do this?  Sorry if I missed it!)

One additional benefit would be having the stack trace.

**Comment by scothis** [comment]
👍, we should be able to convert actual errors into an Error instance, or call `Error.captureStackTrace`.

My hesitation with converting all rejected values to be Errors is that not all rejected values should be Error types. There's a difference between being unable to make an HTTP request, and making an HTTP request whose status was 4xx or 5xx (with the error interceptor installed).

Let me think about this a bit more. It should be possible to make this mostly transparent to uses who currently use simple objects, as long as they don't depend on object identity.

**Comment by briancavalier** [comment]
> There's a difference between being unable to make an HTTP request, and making an HTTP request whose status was 4xx or 5xx

Yeah, agreed.

> Let me think about this a bit more

Sure.  Happy to send a PR for whatever approach you think is best.

**Comment by briancavalier** [comment]
Any more thoughts on this, @scothis?

**Comment by scothis** [comment]
rest.js is no longer maintained
