### ISSUE TITLE
timeout interceptor --> mime-deserialization error

### ISSUE THREAD

**Issue by atomfried** [cujojs/rest#158]
Hi there,

I'm using 2.0.0 and I'm wrapping with template and mime so far. Adding timeout leads to odd behavior.

    require('rest)'
    .wrap(template)
    .wrap(mime)
    .wrap(timeout, {timeout: 3000})
    ({
       // url etc.
    }).then(res => {
      console.log(res);
    })
    .catch(err => {
      console.log(err);
    });

**Successful reponses (status 200, body complete) are being rejected.** 
First of all, I noticed that the response object (which is passed to catch) contains (only when using timeout):

    error: 'mime-deserialization',
    cause: [SyntaxError: Unexpected token o] }

I don't know how to get more information on this error.

Second, the request **does not** time out within 3 seconds.

Any ideas?

Take care

M

**Comment by atomfried** [comment]
The try-catch-notation is not the issue btw. I tried [the notation in the docs](https://github.com/cujojs/rest/blob/4bd359df2df845eda628d2256fd06bc4a1f5009c/docs/interceptors.md#module-rest/interceptor/timeout) to the same result.

**Comment by atomfried** [comment]
Nevermind. 
It was a stupid typo somewhere -- as expected since this project seems well maintained.
Sorry to bother you and thanks for the good work!

M

**Comment by scothis** [comment]
I ❤️ issues that get resolved before I make it to the office for the day.
