### ISSUE TITLE
Fetch API

### ISSUE THREAD

**Issue by rashtao** [cujojs/rest#161]
Is there any plan about making this library compliant with the Fetch APIs [https://fetch.spec.whatwg.org](https://fetch.spec.whatwg.org) ?

I would suggest to make the base client module fully compliant with the Fetch API, eg:
```js
client('http://httpbin.org/post', { method: 'POST', body: 'a=1' })
    .then(res => res.json())
    .then(json => console.log(json));
```

and on top of it keeping the great wrapping patterns to apply interceptors, eg:

```js
mimeClient = client.wrap(mime);
mimeClient('http://httpbin.org/post', { method: 'POST', body: 'a=1' })
    .then(res => res.json())
    .then(json => console.log(json));
```

If I am correct, this would mean replacing the module `rest/client` with a Fetch API client (browser native, polyfill, or Node.js implementations), delegating those functionalities to external modules.
It should be perfectly safe, since the present implementations (and upcoming ones) are expected to strictly implement the API specification.

In general I think this approach would simplify the maintenance of this library and offer a broad compatibility level.

**Comment by scothis** [comment]
I completely agree. I've been thinking about updating interceptors to work with the Fetch API. One wrinkle is with async requests. A promise contains a single value, while the `fetch` method accepts two arguments. Interceptors would need to composite these. There are likely other issues in the response object that will need to be addressed.

**Comment by scothis** [comment]
rest.js is no longer maintained
