### ISSUE TITLE
Does this library can be set to get responseType to "arraybuffer"

### ISSUE THREAD

**Issue by jexamd** [cujojs/rest#168]
Is it possible to set in your library the setting responseType=arraybuffer like in xhr : xhr.responseType in order to get raw data in order to get data byte from a pdf file in a rest api call ?

**Comment by leonardovillela** [comment]
I have the same doubt.

**Comment by scothis** [comment]
You should be able to set the `responseType` value on the `requests.mixin` object. The content of the `mixin` property is applied to the XHR object before the request is sent. Interceptors that manipulate the response could get confused, but in general they should leave it alone.

https://github.com/cujojs/rest/blob/master/docs/clients.md#xmlhttpreqest-client

For example:

```
rest({
  method: 'GET',
  path: '/path/to/binary/resource',
  mixin: {
    responseType: 'arraybuffer'
  }
}).then(...);
```

**Comment by leonardovillela** [comment]
Hello, this solution actually worked, but when my responseType of the request is blob the responseText attribute is not present in the response of the request, there is only the response attribute filled, I do not see why not use the response attribute, I will submit a PR resolving this problem.

https://github.com/cujojs/rest/blob/master/client/xhr.js#L127

**Comment by scothis** [comment]
rest.js is no longer maintained
