### ISSUE TITLE
Why are _embedded and _links non-enumerable?

### ISSUE THREAD

**Issue by priecint** [cujojs/rest#171]
Hi,

was wondering why are _embedded and _links made [non-enumerable](https://github.com/cujojs/rest/blob/master/mime/type/application/hal.js#L50-L51)?

I had to bypass this by making them explicitly enumerable because non-enumerable properties are not included in [spread operator](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Operators/Spread_operator#Spread_in_object_literals).

Thanks

**Comment by scothis** [comment]
@priecint, the `_link` and `_embed` properties are non-enumerable for HAL entities to help facilitate PUT requests back to the resource after modifying the content, as non-enumerable properties will not be serialized by `JSON.stringify()`. 

For your use case, I'd recommend forking the HAL MIME converter and modify it for your needs and [install it back into the MIME registry](https://github.com/cujojs/rest/blob/master/docs/mime.md#custom-converters). If you don't want to change the default behavior, a child registery can be created that extends from the default registry, the gotcha is that the child registry will need to be passed into the [config for the MIME interceptor](https://github.com/cujojs/rest/blob/master/docs/interceptors.md#module-rest/interceptor/mime).
