### ISSUE TITLE
XHR sends string 'undefined' as request body in IE11

### ISSUE THREAD

**Issue by bhamme** [cujojs/rest#178]
If the request given to the XHR client doesn't include an `entity` prop, xhr.js sends `undefined` to `XMLHttpRequest.send` which seems to change the content header if run in IE11. It seems like other libraries get around this by just checking for `undefined` and passing `null` instead: 
https://github.com/axios/axios/issues/248
https://github.com/aurelia/http-client/issues/41

Think xhr.js just needs to be modified to perform that check as well
```
entity = request.entity || null;
...
client.send(entity);
```

In the meantime the workaround is just to explicitly pass in a null entity in the request.

**Comment by scothis** [comment]
rest.js is no longer maintained
