### ISSUE TITLE
Access methods of interceptor

### ISSUE THREAD

**Issue by Doogiemuc** [cujojs/rest#183]
I have written a [cachingInterceptor](https://github.com/Doogiemuc/liquido-vue-frontend/blob/master/src/services/cachingInterceptor.js).  Basically my interceptor is structured very similar to the [pathPrefix.js](https://github.com/cujojs/rest/blob/master/interceptor/pathPrefix.js) example.  

The pathPrefix example has two "private" methods startsWidth() and endsWith().   My cachingInterceptor als has methods like this, e.g.   purgeCache()   or  setTTL()

=> How can I make these methods accessible from a module that only knonws the outer cujoJS rest "client".  I mean, the client that might be wrapped in several interceptors.

````
var client = rest.wrap(mime, { mime: 'application/json'} )  // then convert entity according to mime type
                 .wrap(cachingInterceptor)      // caching interceptor must be BEFORE the mime interceptor!
                 .wrap(errorCode)               // Promise.reject() responses with http status code >= 400 
                 .wrap(logRequestsInterceptor, { logPayload: true })  // first of all log the request
                 .wrap(pathPrefix, { prefix: process.env.backendBaseURL })  // add path prefix to request

// <= how can I access the purgeCache() method inside my cachingInterceptor  from here, knowing only the client variable?

````

**Comment by Doogiemuc** [comment]
Still no idea.  Please help.  Anyone?

**Comment by scothis** [comment]
Interceptors can receive configuration when they wrap a client. That config is passed into each [interceptor phase method](https://github.com/cujojs/rest/blob/master/docs/interceptors.md#interceptor-custom).

```
const cachingInterceptor = interceptor({
  request(req, config) {
    ...
  },
  response(res, config) {
    ...
  }
});

rest.wrap(cachingInterceptor, { cache: cacheImpl })
```

**Comment by Doogiemuc** [comment]
Thank you for that tip. It worked fine.
