### ISSUE TITLE
Add maxTries property to the retry interceptor

### ISSUE THREAD

**Issue by JimBledsoe** [cujojs/rest#184]
The retry interceptor allow easy cascading retries and can be used with the timeout interceptor to give an overall timeout for the retries, but sometimes just a simple retry once or twice is all you want.

Add an additional maxTries property to the init function that will:
- Unspecified: set maxTries to infinity (mimics current behavior)
- 0: essentially the same as unspecified - set to Infinity
- 1-N: Make 1-N attempts at the fetch before rejecting the request

Example:
    const client = rest.wrap(retry, { maxTries: 3 });  // One try plus two retries

**Comment by scothis** [comment]
rest.js is no longer maintained
