### ISSUE TITLE
responseType: 'arraybuffer' causes 'Failed to read the 'responseText' error

### ISSUE THREAD

**Issue by Nikitakun** [cujojs/rest#188]
When creating a client, if I add responseType: 'arraybuffer' to the mixin property, an exception is thrown after request is done. It goes that on line 127 in xhr.js it 'Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').'
Is there a way to bypass it?

**Comment by scothis** [comment]
rest.js is no longer maintained
