### ISSUE TITLE
HTTP 1.1 cache interceptor

### ISSUE THREAD

**Issue by scothis** [cujojs/rest#29]
Implement a client side HTTP 1.1 compliant cache as an interceptor.  Browsers automatically provide a cache, but Node does not.

The low level cache impl should be a plugable strategy.

**Comment by cristiammercado** [comment]
+1

**Comment by Doogiemuc** [comment]
+1

But keep in mind that caching (done correctly!) is a large thing. Think about TTL, removing of (url prefix based) keys in the cache etc.    So maybe it would be better to combine cujojs with something like node-cache lib.   I'll give it a try ...

**Comment by Doogiemuc** [comment]
I managed to write a JuJoJS caching interceptor.    Its open source. Feel free to build upon it:

https://github.com/Doogiemuc/liquido-vue-frontend/blob/master/src/services/cachingInterceptor.js

It has support for TTL, delete entries by URL prefix  (e.g. delete all cache entries for a given REST resource) and clean ES6 code that is well documented.

**Comment by scothis** [comment]
rest.js is no longer maintained
