### ISSUE TITLE
rfc6570 support - URI Template

### ISSUE THREAD

**Issue by scothis** [cujojs/rest#30]
http://tools.ietf.org/html/rfc6570

**Comment by scothis** [comment]
landed on the 'dev' branch

@gregturn care to give it a spin?

**Comment by gregturn** [comment]
@scothis Absolutely! I'll let you know when I can update my demo app, which maximizes usage of restJS.

**Comment by gregturn** [comment]
I finally check this out. Perfect! You can [see my edits to start using it](https://github.com/gregturn/spring-a-gram/commit/4ceaeeddd3666a4e669c80972250e7e7cb3a3153) after migrating BACK to bower (when I figured out how to beat maven/npm into supporting bower).
