### ISSUE TITLE
Use of beget() for config object complicates logging/debugging

### ISSUE THREAD

**Issue by bgmort** [cujojs/rest#61]
Because the beget() function returns an object with the original object as the new object's prototype instead of attaching the properties directly to the new object, operations such as console.log and JSON.stringify do not work as expected on objects produced by beget().  More concretely, the config object that is passed around in an interceptor hides its properties from console.log and JSON.stringify.

I did a quick and dirty test using a simpler approach with a flat object that seems like it could work just as well, at least for the interceptor's config object:

	function clone(obj, props) {
		var tmp = {};
		mixin(tmp, obj);
		if (props) {
			mixin(tmp, props);
		}
		return tmp;
	}

I can see that this would be slightly less performant with a larger, more complex object, but the difference would be small.  If it is not feasible to change the implementation, I think it would be worth at least mentioning the quirks of beget() and therefore the interceptor config object, because its surprising and unexpected behavior makes writing custom interceptors more challenging.

I'll mention, since it could be useful to others, that I am using the following in my custom interceptor for debugging purposes.  Note that this negates any performance advantages of using prototypal inheritance inside beget():

    init: function(config){
        for (var k in config) config[k] = config[k];
        ...
    }

**Comment by scothis** [comment]
fixed on dev branch
