### ISSUE TITLE
'mime-unknown' error thrown for requests with content type not in mime interceptor registry

### ISSUE THREAD

**Issue by itkach** [cujojs/rest#88]
This appears to be intentional design and I'd like to make a case that this is not very good. Consider a  client wrapped in several interceptors, including mime, is used to make various requests to a web service that accepts and returns mostly json, but also some opaque data with, for example, `application/octet-stream` content type, say for an unprocessed image data or some binary token captured by the application (think Phonegap with plugins giving access to device hardware). With current implementation, response falls back to plain text handler and leaves content unmodified. Request, on the other hand, for some reason throws an error instead of leaving original request unmodified. Adding content types to registry with serializer/deserializer that does nothing works, but it's extra code for no apparent benefit.

**Comment by scothis** [comment]
@itkach I added an opt-in to mime interceptor config to ignore the mime-unknown error. Please reopen if this doesn't fit your needs.
