### ISSUE TITLE
webpack errors

### ISSUE THREAD

**Issue by braco** [cujojs/rest#89]
```
./~/rest/mime/registry.js
Critical dependencies:
81:4-11 require function is used in a way, in which dependencies cannot be statically extracted
86:23-30 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/rest/mime/registry.js 81:4-11 86:23-30 
```

[registry.js line 81](https://github.com/cujojs/rest/blob/master/mime/registry.js#L81)

Anyone know of a way to get rid of these errors? It pollutes both console and terminal constantly. I see these listed as benign in #83, but this is not ideal.

**Comment by scothis** [comment]
@pozadi there are a few loose ends to tie up before 1.3.0, shouldn't be too long. Hopefully within a week.
