### ISSUE TITLE
Ability to monitor request progress

### ISSUE THREAD

**Issue by alh84001** [cujojs/rest#91]
It would be useful to be able to have access to (XHR) client progress, ideally through the promise returned. If that is not feasible at least the ability to mixin progress listener would be nice. Currently XHR client is created, then it is opened, and then the properties are mixed in. For download progress it would be sufficient to do the mixing ('onprogress' property) before opening the connection, but this won't work for upload progress.

(edit: I see now that this is somewhat related to issue #79 as well)

**Comment by scothis** [comment]
Closing in favor of #101
