### ISSUE TITLE
Android 4.0.4 & 4.1.2: `INVALID_STATE_ERR: DOM Exception 11` when processing the server response

### ISSUE THREAD

**Issue by ouadi** [cujojs/rest#93]
I have a strange issue when running my mobile application using Android versions 4.0.4 and 4.1.2 (the issue might exist in other versions too). The same application works fine in other versions of Android both older (2.3.4 for instance) and newer (4.4.2 for instance).

The issue is as follows (see code below):
- I initiate an HTTP GET to the server
- The server receives request, process it and sends back the response to the mobile application
- The response is rejected with the following error: `{"message":"INVALID_STATE_ERR: DOM Exception 11","name":"INVALID_STATE_ERR","code":11}`

``` javascript
return rest(request)
.then(function(response){
    logger.info('... received response [' + JSON.stringify(response) + '].');
}).otherwise(function(response){
    logger.info('... received error [' + JSON.stringify(response) + '].');
});
```

I have googled this error for a good time. SO contains many questions related to it. However, all suggested solutions are already implemented in `rest/client/xhr.js`:
- XMLHttpRequest.open() should be called before XMLHttpRequest.setRequestHeader()
- status should be accessed only when readyState is at 4

I can't take this issue right now to Android developer forums. Using the same mobiles were my application fails, I'm able to access my server from a browser. So, it is not an issue with Android but rather with the client used to access the server that is `rest` in my case.

Can you, please, suggest a direction in order to resolve my problem? In the mean time, I will try to use jQuery.ajax() method.

Cheers.

**Comment by scothis** [comment]
rest.js is no longer maintained
