### ISSUE TITLE
Retrying slow / timed out requests

### ISSUE THREAD

**Issue by optical** [cujojs/rest#94]
I am trying to write a client which will handle slow requests gracefully. It should timeout if a single request takes too long, back off, and try again. Then after a longer period of time it should call it quits and fail. It doesn't look like this can be accomplished using the existing timeout and retry interceptors as the timeout interceptor cancels the request, and the retry interceptor will not retry cancelled requests.

Perhaps the timeout interceptor could be configured to not cancel the request?
Ideally it would look something like this

	var client = rest.wrap(timeoutInterceptor, { timeout: 5000, cancel: false }) // Give up after 5 seconds.
	.wrap(retryInterceptor) // Retry timed out individual requests.
	.wrap(timeoutInterceptor, { timeout: 120000 }); // Give up after retrying for a long period of time.

**Comment by scothis** [comment]
@optical this makes sense. I tend to shy away from opt-in config values that are set to false. What do you think of `{ transient: true }` to prevent permanent cancelation?

Are you willing to put together a pull request? I'd like to get 1.3 out this weekend, or early next week.

**Comment by optical** [comment]
@scothis Yep that sounds find to me. I'll have a go at implementing it today.

**Comment by scothis** [comment]
resolved by #97
