### ISSUE TITLE
Support multipart/form-data for node client

### ISSUE THREAD

**Issue by vincentjames501** [cujojs/rest#98]
I've tried using an HTML5 polyfill library for FormData, File, Blob, etc, but looks like there are several issues preventing this from working:

1) The content-length will need to be computed differently as an entity that's of type FormData will fail to get the length properly.

``` javascript
if (!headers['Content-Length']) {
    headers['Content-Length'] = entity ? Buffer.byteLength(entity, 'utf8') : 0;
}
```

2) This doesn't seem to work with a FormData object unfortunately.

``` javascript
if (entity) {
    clientRequest.write(entity);
}
```

**Comment by scothis** [comment]
@vincentjames501 Do you have suggestions? Without knowing the polyfill you're using, it's difficult to know what actions to take.

**Comment by vincentjames501** [comment]
I haven't looked into it much, but the ```request``` library is using [https://github.com/felixge/node-form-data](form-data) to handle it's multipart/form-data requests. They have an example in their README on how to use it with ```http```, so it may be worthwhile to see how ```request``` is using it?

**Comment by scothis** [comment]
rest.js is no longer maintained
