### ISSUE TITLE
Convert source to ES6

### ISSUE THREAD

**Issue by scothis** [cujojs/rest#99]
It may be too soon for this, but I'd like to explore converting rest.js to use ES6.

For bowser consumers, we could publish a pre-transpiled version. Support both traceur and 6to5.

**Comment by davidchase** [comment]
@scothis seems like you have this mostly handled in the [promise branch](https://github.com/cujojs/rest/tree/promise) anything else needed to help bring this to rest master/npm ?

it would be a nice to have and i could help out if needed

**Comment by scothis** [comment]
@davidchase The open question is distribution. Current releases are available via npm, bower and jspm. With npm we can compile es6 to es5 before publishing. Bower doesn't have such a hook and expects compile sources to be in the repo. I'm enough out of the loop on jspm that I'm not sure, but I think it can handle es6 natively.

Open to ideas and contributions. My day job has kept me pretty busy.

Longer term, I've been keeping an eye on `fetch()`. I'd like to get out of the business of maintaining the low level clients and focus instead on composable interceptors. fetch combined with WHATWG Streams provide a lot of interesting opportunities. I've wanted to do streaming interceptors for a long time, but browser support has been an impediment.

**Comment by davidchase** [comment]
yeah sorry, i commented on the wrong issue, i meant this specific question to be on the dropping `when` as a dependency... (guess i clicked through to this issue) i can remove and re-post that comment in the correct issue if needed.

> ... instead on composable interceptors

thats been the very reason i use rest.js at work

but i think for the es6 part of it, is might as well start moving in that direction and worry about npm/bower i guess for now... i can help out with that as well if needed

**Comment by scothis** [comment]
The only reason I didn't merge the promises branch is because I was unsure of the version number it should receive. Thinking now, it's needs to be 2.0 since it could break users.

**Comment by scothis** [comment]
rest.js is no longer maintained
